### User Register

POST http://localhost:4000/user-api/users
Content-Type: application/json

{
    "firstName":"Anurag new",
    "lastName":"Sharma",
    "email":"anurag.user123@example.com",
    "password":"Author@12345",
    "profileimageUrl":"https://example.com/avatars/author.png"
    

}

###user login

POST http://localhost:4000/user-api/authenticate
Content-Type: application/json

{
    "email":"anurag.user123@example.com",
    "password":"Author@12345",
    "role":"USER"
}
### Author register

POST http://localhost:4000/author-api/users
Content-Type: application/json

{
    "firstName":"vilok",
    "lastName":"kumar",
    "email":"vilok.kumar123@example.com",
    "password":"Author@12345",
    "profileimageUrl":"https://example.com/avatars/author.png"
    
}

### Author or user login

POST http://localhost:4000/common-api/authenticate
Content-Type: application/json

{
"email":"sujankowshik@gmail.com",
"password":"sujan@123"
}

###create article(author)

POST http://localhost:4000/author-api/articles
Content-Type: application/json

{
    "author":"69896cf4e166fb5c7f695635",
    "title":"test1 article",
    "category":"programming",
    "content":"test1 content"
}

###read articles

GET http://localhost:4000/author-api/articles/69896cf4e166fb5c7f695635

### update article

PUT http://localhost:4000/author-api/articles
Content-Type: application/json

{
    "author":"69896cf4e166fb5c7f695635",
    "articleId":"698974826ac924df852ddde7",
    "title":"test2 article",
    "category":"programming",
    "content":"test2 content"
}

###delete article

PUT http://localhost:4000/author-api/delarticle
Content-Type: application/json

{
    "author":"69896cf4e166fb5c7f695635",
    "articleId":"698974826ac924df852ddde7"
}

###logout
POST http://localhost:4000/logout

###read all articles as user
GET http://localhost:4000/user-api/articles

###add comment as user
PUT http://localhost:4000/user-api/comment
Content-Type: application/json

{
    "user":"69896780f55b9cdc3ba27425",
    "articleid":"698974826ac924df852ddde7",
    "comment":"commenting the article!!"
}

###testing an invalid path
GET http://localhost:4000/test

### blocking the user

PUT http://localhost:4000/admin-api/block/69896aac8c38b2825392a9fe

### unblocking the user

PUT http://localhost:4000/admin-api/unblock/69896aac8c38b2825392a9fe

### changing the password

PUT http://localhost:4000/common-api/change
Content-Type: application/json

{
    "email":"vilok.kumar123@example.com",
    "password":"",
    "newpassword":"Author@12"
}
